release.yml: Get & check schema version early

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -54,6 +54,15 @@ jobs:
         run: python -m pip install .
         working-directory: dandischema
 
+      - name: Get schema version
+        run: |
+          SCHEMA_VERSION="$(python -c 'from dandischema.consts import DANDI_SCHEMA_VERSION; print(DANDI_SCHEMA_VERSION)')"
+          if ! echo "$SCHEMA_VERSION" | grep -qP '^\d+\.\d+\.\d+$'
+          then printf "[ERROR] Invalid schema version: '%s'\n" "$SCHEMA_VERSION"
+               exit 1
+          fi
+          echo "SCHEMA_VERSION=$SCHEMA_VERSION" >> "$GITHUB_ENV"
+
       - name: Checkout dandi/schema
         uses: actions/checkout@v2
         with:
@@ -96,7 +105,6 @@ jobs:
       - name: Commit schema changes and create new tag
         run: |
           LIBRARY_VERSION="$(git -C ../dandischema describe --tags --exact-match)"
-          SCHEMA_VERSION="$(python -c 'from dandischema.consts import DANDI_SCHEMA_VERSION; print(DANDI_SCHEMA_VERSION)')"
 
           git config --global user.email "team@dandiarchive.org"
           git config --global user.name "DANDI Bot"
